name: Sage Books Command Center
on:
  workflow_dispatch:
    inputs:
      task:
        description: 'Run Specific Task'
        required: true
        type: choice
        options:
          - 'Build Debug APK'
          - 'Build Release APK'
          - 'Analyze'
          - 'Clean'
          - 'Pub Get'
          - 'Pub Outdated'
          - 'Signing Report'

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.38.5'

      # Task: Flutter Clean
      - name: Flutter Clean
        if: github.event.inputs.task == 'Clean'
        run: flutter clean

      # Task: Flutter Pub Get
      - name: Flutter Pub Get
        if: github.event.inputs.task == 'Pub Get'
        run: flutter pub get

      # Task: Flutter Pub Outdated
      - name: Flutter Pub Outdated
        if: github.event.inputs.task == 'Pub Outdated'
        run: flutter pub outdated

      # Task: Flutter Analyse
      - name: Flutter Analyse
        if: github.event.inputs.task == 'Analyze'
        run: flutter analyze .

      # Task: Build APK Debug
      - name: Build APK Debug
        if: github.event.inputs.task == 'Build Debug APK'
        run: flutter build apk --debug

      # Task: Build APK Release
      - name: Build APK Release
        if: github.event.inputs.task == 'Build Release APK'
        run: flutter build apk --release --no-tree-shake-icons

     # Task: Android Signing Report
      - name: Android Signing Report
        if: github.event.inputs.task == 'Signing Report'
        run: |
          # 1. Enter the android directory
          cd android
          
          # 2. Check if gradlew exists, if not, try to generate it
          if [ ! -f "gradlew" ]; then
            echo "gradlew missing! Attempting to restore from Flutter..."
            flutter build apk --debug --dry-run
          fi
          
          # 3. Grant permission and run
          chmod +x gradlew
          ./gradlew signingReport


      # Upload Artifacts (Only if a Build task was chosen)
      - name: Upload APK
        if: contains(github.event.inputs.task, 'Build')
        uses: actions/upload-artifact@v4
        with:
          name: SageBooks-APK
          path: build/app/outputs/flutter-apk/*.apk
